<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // find category by slug
        $cat = fn(string $slug) => Category::where('slug', $slug)->firstOrFail();

        $products = [
            // ===================== CLOTHES =====================
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-001',
                'name' => 'Premium Cotton T-Shirt',
                'price' => 14.99,
                'stock' => 150,
                'image_url' => 'https://picsum.photos/seed/clothes-001/800/800',
                'description' => 'Premium quality cotton t-shirt for everyday wear.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-002',
                'name' => 'Classic Oxford Shirt',
                'price' => 29.99,
                'stock' => 100,
                'image_url' => 'https://picsum.photos/seed/clothes-002/800/800',
                'description' => 'Timeless oxford shirt perfect for office and casual.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-003',
                'name' => 'Casual Hoodie',
                'price' => 34.99,
                'stock' => 80,
                'image_url' => 'https://picsum.photos/seed/clothes-003/800/800',
                'description' => 'Comfortable hoodie for casual outings.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-004',
                'name' => 'Slim Fit Pants',
                'price' => 39.99,
                'stock' => 90,
                'image_url' => 'https://picsum.photos/seed/clothes-004/800/800',
                'description' => 'Modern slim fit pants with stretch fabric.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-005',
                'name' => 'Summer Dress',
                'price' => 32.99,
                'stock' => 70,
                'image_url' => 'https://picsum.photos/seed/clothes-005/800/800',
                'description' => 'Light and breathable dress for summer.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-006',
                'name' => 'Denim Jacket',
                'price' => 49.99,
                'stock' => 60,
                'image_url' => 'https://picsum.photos/seed/clothes-006/800/800',
                'description' => 'Classic denim jacket for all seasons.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-007',
                'name' => 'Polo Shirt',
                'price' => 24.99,
                'stock' => 110,
                'image_url' => 'https://picsum.photos/seed/clothes-007/800/800',
                'description' => 'Elegant polo shirt with collar detail.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-008',
                'name' => 'Sweatshirt',
                'price' => 27.99,
                'stock' => 95,
                'image_url' => 'https://picsum.photos/seed/clothes-008/800/800',
                'description' => 'Cozy sweatshirt for comfort and style.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-009',
                'name' => 'Linen Shirt',
                'price' => 28.99,
                'stock' => 75,
                'image_url' => 'https://picsum.photos/seed/clothes-009/800/800',
                'description' => 'Breathable linen shirt perfect for warm weather.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-010',
                'name' => 'Graphic Tee',
                'price' => 16.99,
                'stock' => 130,
                'image_url' => 'https://picsum.photos/seed/clothes-010/800/800',
                'description' => 'Cool graphic printed t-shirt with unique design.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-011',
                'name' => 'Cardigan Sweater',
                'price' => 42.99,
                'stock' => 65,
                'image_url' => 'https://picsum.photos/seed/clothes-011/800/800',
                'description' => 'Stylish cardigan sweater layering piece.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-012',
                'name' => 'Striped Long Sleeve',
                'price' => 22.99,
                'stock' => 105,
                'image_url' => 'https://picsum.photos/seed/clothes-012/800/800',
                'description' => 'Classic striped long sleeve shirt for all seasons.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-013',
                'name' => 'Chino Pants',
                'price' => 38.99,
                'stock' => 85,
                'image_url' => 'https://picsum.photos/seed/clothes-013/800/800',
                'description' => 'Comfortable chino pants for business casual.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-014',
                'name' => 'V-Neck T-Shirt',
                'price' => 15.99,
                'stock' => 140,
                'image_url' => 'https://picsum.photos/seed/clothes-014/800/800',
                'description' => 'Flattering v-neck t-shirt in multiple colors.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-015',
                'name' => 'Wrap Dress',
                'price' => 44.99,
                'stock' => 50,
                'image_url' => 'https://picsum.photos/seed/clothes-015/800/800',
                'description' => 'Elegant wrap dress perfect for any occasion.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-016',
                'name' => 'Cargo Pants',
                'price' => 41.99,
                'stock' => 70,
                'image_url' => 'https://picsum.photos/seed/clothes-016/800/800',
                'description' => 'Practical cargo pants with multiple pockets.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-017',
                'name' => 'Thermal Long Sleeve',
                'price' => 19.99,
                'stock' => 110,
                'image_url' => 'https://picsum.photos/seed/clothes-017/800/800',
                'description' => 'Warm thermal long sleeve for cold weather.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-018',
                'name' => 'Maxi Skirt',
                'price' => 35.99,
                'stock' => 60,
                'image_url' => 'https://picsum.photos/seed/clothes-018/800/800',
                'description' => 'Flowing maxi skirt for elegant style.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-019',
                'name' => 'Windbreaker Jacket',
                'price' => 45.99,
                'stock' => 55,
                'image_url' => 'https://picsum.photos/seed/clothes-019/800/800',
                'description' => 'Lightweight windbreaker perfect for active wear.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-020',
                'name' => 'Button-Up Vest',
                'price' => 31.99,
                'stock' => 75,
                'image_url' => 'https://picsum.photos/seed/clothes-020/800/800',
                'description' => 'Versatile button-up vest for layering.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-021',
                'name' => 'Flannel Shirt',
                'price' => 26.99,
                'stock' => 95,
                'image_url' => 'https://picsum.photos/seed/clothes-021/800/800',
                'description' => 'Cozy flannel shirt for casual comfort.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-022',
                'name' => 'Skinny Jeans',
                'price' => 42.99,
                'stock' => 80,
                'image_url' => 'https://picsum.photos/seed/clothes-022/800/800',
                'description' => 'Modern skinny jeans with trendy fit.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-023',
                'name' => 'Crop Top',
                'price' => 18.99,
                'stock' => 125,
                'image_url' => 'https://picsum.photos/seed/clothes-023/800/800',
                'description' => 'Fashionable crop top for summer style.',
            ],
            [
                'category' => 'clothes',
                'sku' => 'CLOTHES-024',
                'name' => 'Blazer Jacket',
                'price' => 54.99,
                'stock' => 45,
                'image_url' => 'https://picsum.photos/seed/clothes-024/800/800',
                'description' => 'Professional blazer for business attire.',
            ],

            // ===================== SHOES =====================
            [
                'category' => 'shoes',
                'sku' => 'SHOES-001',
                'name' => 'Running Sneakers',
                'price' => 59.99,
                'stock' => 80,
                'image_url' => 'https://picsum.photos/seed/shoes-001/800/800',
                'description' => 'High-performance running shoes with cushioned sole.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-002',
                'name' => 'Casual Sneakers',
                'price' => 44.99,
                'stock' => 120,
                'image_url' => 'https://picsum.photos/seed/shoes-002/800/800',
                'description' => 'Versatile sneakers for everyday wear.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-003',
                'name' => 'Basketball Shoes',
                'price' => 79.99,
                'stock' => 50,
                'image_url' => 'https://picsum.photos/seed/shoes-003/800/800',
                'description' => 'Professional basketball shoes with ankle support.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-004',
                'name' => 'Formal Loafers',
                'price' => 64.99,
                'stock' => 40,
                'image_url' => 'https://picsum.photos/seed/shoes-004/800/800',
                'description' => 'Elegant loafers for formal occasions.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-005',
                'name' => 'Hiking Boots',
                'price' => 89.99,
                'stock' => 35,
                'image_url' => 'https://picsum.photos/seed/shoes-005/800/800',
                'description' => 'Durable hiking boots with waterproof material.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-006',
                'name' => 'Sandals',
                'price' => 29.99,
                'stock' => 100,
                'image_url' => 'https://picsum.photos/seed/shoes-006/800/800',
                'description' => 'Comfortable sandals perfect for summer.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-007',
                'name' => 'Chelsea Boots',
                'price' => 74.99,
                'stock' => 45,
                'image_url' => 'https://picsum.photos/seed/shoes-007/800/800',
                'description' => 'Stylish Chelsea boots for any season.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-008',
                'name' => 'Sports Slip-On',
                'price' => 39.99,
                'stock' => 85,
                'image_url' => 'https://picsum.photos/seed/shoes-008/800/800',
                'description' => 'Easy-to-wear sports slip-on shoes.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-009',
                'name' => 'Oxfords',
                'price' => 69.99,
                'stock' => 50,
                'image_url' => 'https://picsum.photos/seed/shoes-009/800/800',
                'description' => 'Classic oxford shoes for professional look.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-010',
                'name' => 'Flip Flops',
                'price' => 12.99,
                'stock' => 200,
                'image_url' => 'https://picsum.photos/seed/shoes-010/800/800',
                'description' => 'Lightweight flip flops for casual comfort.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-011',
                'name' => 'Tennis Shoes',
                'price' => 54.99,
                'stock' => 75,
                'image_url' => 'https://picsum.photos/seed/shoes-011/800/800',
                'description' => 'Professional tennis shoes with grip sole.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-012',
                'name' => 'Boat Shoes',
                'price' => 49.99,
                'stock' => 65,
                'image_url' => 'https://picsum.photos/seed/shoes-012/800/800',
                'description' => 'Nautical style boat shoes for casual wear.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-013',
                'name' => 'Ankle Boots',
                'price' => 64.99,
                'stock' => 55,
                'image_url' => 'https://picsum.photos/seed/shoes-013/800/800',
                'description' => 'Trendy ankle boots for fashion forward look.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-014',
                'name' => 'Dress Pumps',
                'price' => 59.99,
                'stock' => 48,
                'image_url' => 'https://picsum.photos/seed/shoes-014/800/800',
                'description' => 'Elegant dress pumps for formal events.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-015',
                'name' => 'Work Boots',
                'price' => 84.99,
                'stock' => 40,
                'image_url' => 'https://picsum.photos/seed/shoes-015/800/800',
                'description' => 'Sturdy work boots with steel toe protection.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-016',
                'name' => 'Moccasins',
                'price' => 44.99,
                'stock' => 70,
                'image_url' => 'https://picsum.photos/seed/shoes-016/800/800',
                'description' => 'Cozy moccasins for comfort at home.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-017',
                'name' => 'Cross Training',
                'price' => 64.99,
                'stock' => 60,
                'image_url' => 'https://picsum.photos/seed/shoes-017/800/800',
                'description' => 'Versatile cross training shoes for gym.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-018',
                'name' => 'Skate Shoes',
                'price' => 54.99,
                'stock' => 50,
                'image_url' => 'https://picsum.photos/seed/shoes-018/800/800',
                'description' => 'Durable skate shoes with ankle protection.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-019',
                'name' => 'Ballet Flats',
                'price' => 34.99,
                'stock' => 90,
                'image_url' => 'https://picsum.photos/seed/shoes-019/800/800',
                'description' => 'Elegant ballet flats for everyday wear.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-020',
                'name' => 'Winter Boots',
                'price' => 94.99,
                'stock' => 30,
                'image_url' => 'https://picsum.photos/seed/shoes-020/800/800',
                'description' => 'Insulated winter boots for cold weather.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-021',
                'name' => 'Espadrilles',
                'price' => 39.99,
                'stock' => 85,
                'image_url' => 'https://picsum.photos/seed/shoes-021/800/800',
                'description' => 'Breathable espadrilles for warm days.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-022',
                'name' => 'Wedge Sandals',
                'price' => 44.99,
                'stock' => 70,
                'image_url' => 'https://picsum.photos/seed/shoes-022/800/800',
                'description' => 'Comfortable wedge sandals with height.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-023',
                'name' => 'Platform Sneakers',
                'price' => 54.99,
                'stock' => 65,
                'image_url' => 'https://picsum.photos/seed/shoes-023/800/800',
                'description' => 'Trendy platform sneakers for height.',
            ],
            [
                'category' => 'shoes',
                'sku' => 'SHOES-024',
                'name' => 'Golf Shoes',
                'price' => 79.99,
                'stock' => 35,
                'image_url' => 'https://picsum.photos/seed/shoes-024/800/800',
                'description' => 'Professional golf shoes with spike grip.',
            ],

            // ===================== BELTS =====================
            [
                'category' => 'belts',
                'sku' => 'BELT-001',
                'name' => 'Leather Belt - Black',
                'price' => 19.99,
                'stock' => 200,
                'image_url' => 'https://picsum.photos/seed/belt-001/800/800',
                'description' => 'Premium black leather belt for everyday wear.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-002',
                'name' => 'Leather Belt - Brown',
                'price' => 19.99,
                'stock' => 180,
                'image_url' => 'https://picsum.photos/seed/belt-002/800/800',
                'description' => 'Classic brown leather belt versatile for all outfits.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-003',
                'name' => 'Canvas Belt',
                'price' => 14.99,
                'stock' => 150,
                'image_url' => 'https://picsum.photos/seed/belt-003/800/800',
                'description' => 'Lightweight canvas belt for casual style.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-004',
                'name' => 'Silver Buckle Belt',
                'price' => 24.99,
                'stock' => 120,
                'image_url' => 'https://picsum.photos/seed/belt-004/800/800',
                'description' => 'Elegant belt with silver buckle detail.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-005',
                'name' => 'Braided Leather Belt',
                'price' => 29.99,
                'stock' => 100,
                'image_url' => 'https://picsum.photos/seed/belt-005/800/800',
                'description' => 'Sophisticated braided leather belt.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-006',
                'name' => 'Fabric Belt - Colorful',
                'price' => 12.99,
                'stock' => 170,
                'image_url' => 'https://picsum.photos/seed/belt-006/800/800',
                'description' => 'Vibrant fabric belt for fun and colorful looks.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-007',
                'name' => 'Gold Chain Belt',
                'price' => 34.99,
                'stock' => 80,
                'image_url' => 'https://picsum.photos/seed/belt-007/800/800',
                'description' => 'Trendy gold chain belt for fashion statement.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-008',
                'name' => 'Adjustable Web Belt',
                'price' => 16.99,
                'stock' => 140,
                'image_url' => 'https://picsum.photos/seed/belt-008/800/800',
                'description' => 'Comfortable adjustable web belt perfect for sports.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-009',
                'name' => 'Suede Belt - Tan',
                'price' => 26.99,
                'stock' => 110,
                'image_url' => 'https://picsum.photos/seed/belt-009/800/800',
                'description' => 'Soft suede belt in warm tan color.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-010',
                'name' => 'Metal Loop Belt',
                'price' => 21.99,
                'stock' => 130,
                'image_url' => 'https://picsum.photos/seed/belt-010/800/800',
                'description' => 'Modern metal loop belt for edgy style.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-011',
                'name' => 'Reversible Leather',
                'price' => 32.99,
                'stock' => 90,
                'image_url' => 'https://picsum.photos/seed/belt-011/800/800',
                'description' => 'Reversible leather belt black and brown sides.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-012',
                'name' => 'Chain Link Belt',
                'price' => 28.99,
                'stock' => 85,
                'image_url' => 'https://picsum.photos/seed/belt-012/800/800',
                'description' => 'Stylish chain link belt for fashion edge.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-013',
                'name' => 'Woven Belt',
                'price' => 17.99,
                'stock' => 145,
                'image_url' => 'https://picsum.photos/seed/belt-013/800/800',
                'description' => 'Natural woven belt for casual look.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-014',
                'name' => 'Patent Leather',
                'price' => 25.99,
                'stock' => 105,
                'image_url' => 'https://picsum.photos/seed/belt-014/800/800',
                'description' => 'Shiny patent leather belt for style.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-015',
                'name' => 'Studded Belt',
                'price' => 31.99,
                'stock' => 75,
                'image_url' => 'https://picsum.photos/seed/belt-015/800/800',
                'description' => 'Edgy studded belt for rock style.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-016',
                'name' => 'Elastic Belt',
                'price' => 13.99,
                'stock' => 160,
                'image_url' => 'https://picsum.photos/seed/belt-016/800/800',
                'description' => 'Comfortable elastic belt for flexibility.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-017',
                'name' => 'Corduroy Belt',
                'price' => 20.99,
                'stock' => 120,
                'image_url' => 'https://picsum.photos/seed/belt-017/800/800',
                'description' => 'Textured corduroy belt for casual style.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-018',
                'name' => 'Skinny Metal Belt',
                'price' => 23.99,
                'stock' => 100,
                'image_url' => 'https://picsum.photos/seed/belt-018/800/800',
                'description' => 'Sleek skinny metal buckle belt.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-019',
                'name' => 'Wide Waist Belt',
                'price' => 35.99,
                'stock' => 65,
                'image_url' => 'https://picsum.photos/seed/belt-019/800/800',
                'description' => 'Statement wide waist belt for fashion.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-020',
                'name' => 'Vintage Buckle',
                'price' => 29.99,
                'stock' => 95,
                'image_url' => 'https://picsum.photos/seed/belt-020/800/800',
                'description' => 'Classic vintage style buckle belt.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-021',
                'name' => 'Rope Belt',
                'price' => 18.99,
                'stock' => 130,
                'image_url' => 'https://picsum.photos/seed/belt-021/800/800',
                'description' => 'Natural rope belt for casual nautical look.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-022',
                'name' => 'Silver Chain',
                'price' => 36.99,
                'stock' => 70,
                'image_url' => 'https://picsum.photos/seed/belt-022/800/800',
                'description' => 'Elegant silver chain belt for glamour.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-023',
                'name' => 'Micro Fiber',
                'price' => 22.99,
                'stock' => 115,
                'image_url' => 'https://picsum.photos/seed/belt-023/800/800',
                'description' => 'Durable microfiber belt for durability.',
            ],
            [
                'category' => 'belts',
                'sku' => 'BELT-024',
                'name' => 'Statement Buckle',
                'price' => 38.99,
                'stock' => 60,
                'image_url' => 'https://picsum.photos/seed/belt-024/800/800',
                'description' => 'Bold statement buckle belt for impact.',
            ],

            // ===================== MEN =====================
            [
                'category' => 'men-t-shirts',
                'sku' => 'MEN-TEE-001',
                'name' => 'Men Basic Cotton Tee',
                'price' => 12.90,
                'stock' => 100,
                'image_url' => 'https://picsum.photos/seed/men-tee-1/800/800',
                'description' => 'Soft cotton t-shirt for daily wear.',
            ],
            [
                'category' => 'men-shirts',
                'sku' => 'MEN-SHIRT-001',
                'name' => 'Men Oxford Shirt',
                'price' => 24.50,
                'stock' => 60,
                'image_url' => 'https://picsum.photos/seed/men-shirt-1/800/800',
                'description' => 'Classic oxford shirt for office and casual.',
            ],
            [
                'category' => 'men-pants',
                'sku' => 'MEN-PANT-001',
                'name' => 'Men Slim Fit Pants',
                'price' => 27.90,
                'stock' => 55,
                'image_url' => 'https://picsum.photos/seed/men-pants-1/800/800',
                'description' => 'Slim fit pants with comfortable stretch.',
            ],
            [
                'category' => 'men-shoes',
                'sku' => 'MEN-SHOE-001',
                'name' => 'Men Casual Sneakers',
                'price' => 39.90,
                'stock' => 40,
                'image_url' => 'https://picsum.photos/seed/men-shoes-1/800/800',
                'description' => 'Everyday sneakers for comfort and style.',
            ],

            // ===================== WOMEN =====================
            [
                'category' => 'women-dresses',
                'sku' => 'WOM-DRESS-001',
                'name' => 'Women Summer Dress',
                'price' => 29.90,
                'stock' => 50,
                'image_url' => 'https://picsum.photos/seed/women-dress-1/800/800',
                'description' => 'Lightweight dress for warm days.',
            ],
            [
                'category' => 'women-tops',
                'sku' => 'WOM-TOP-001',
                'name' => 'Women Ribbed Top',
                'price' => 15.00,
                'stock' => 80,
                'image_url' => 'https://picsum.photos/seed/women-top-1/800/800',
                'description' => 'Comfortable ribbed top with modern fit.',
            ],
            [
                'category' => 'women-skirts',
                'sku' => 'WOM-SKIRT-001',
                'name' => 'Women Pleated Skirt',
                'price' => 19.90,
                'stock' => 45,
                'image_url' => 'https://picsum.photos/seed/women-skirt-1/800/800',
                'description' => 'Pleated skirt for casual or formal styling.',
            ],
            [
                'category' => 'women-shoes',
                'sku' => 'WOM-SHOE-001',
                'name' => 'Women Running Shoes',
                'price' => 44.90,
                'stock' => 35,
                'image_url' => 'https://picsum.photos/seed/women-shoes-1/800/800',
                'description' => 'Light running shoes with cushioned sole.',
            ],

            // ===================== BOY =====================
            [
                'category' => 'boy-t-shirts',
                'sku' => 'BOY-TEE-001',
                'name' => 'Boy Graphic Tee',
                'price' => 9.90,
                'stock' => 120,
                'image_url' => 'https://picsum.photos/seed/boy-tee-1/800/800',
                'description' => 'Fun graphic t-shirt for kids.',
            ],
            [
                'category' => 'boy-shorts',
                'sku' => 'BOY-SHORT-001',
                'name' => 'Boy Sport Shorts',
                'price' => 10.90,
                'stock' => 90,
                'image_url' => 'https://picsum.photos/seed/boy-shorts-1/800/800',
                'description' => 'Comfortable shorts for play and sports.',
            ],
            [
                'category' => 'boy-shoes',
                'sku' => 'BOY-SHOE-001',
                'name' => 'Boy Sneakers',
                'price' => 22.90,
                'stock' => 50,
                'image_url' => 'https://picsum.photos/seed/boy-shoes-1/800/800',
                'description' => 'Durable sneakers for everyday wear.',
            ],

            // ===================== GIRL =====================
            [
                'category' => 'girl-dresses',
                'sku' => 'GIRL-DRESS-001',
                'name' => 'Girl Floral Dress',
                'price' => 18.90,
                'stock' => 70,
                'image_url' => 'https://picsum.photos/seed/girl-dress-1/800/800',
                'description' => 'Floral dress perfect for weekends.',
            ],
            [
                'category' => 'girl-tops',
                'sku' => 'GIRL-TOP-001',
                'name' => 'Girl Soft Cotton Top',
                'price' => 8.90,
                'stock' => 95,
                'image_url' => 'https://picsum.photos/seed/girl-top-1/800/800',
                'description' => 'Soft cotton top for daily comfort.',
            ],
            [
                'category' => 'girl-shoes',
                'sku' => 'GIRL-SHOE-001',
                'name' => 'Girl Casual Shoes',
                'price' => 19.90,
                'stock' => 55,
                'image_url' => 'https://picsum.photos/seed/girl-shoes-1/800/800',
                'description' => 'Light shoes for school and weekend.',
            ],
        ];

        foreach ($products as $p) {
            $category = $cat($p['category']);

            Product::updateOrCreate(
                ['slug' => Str::slug($p['name'])],
                [
                    'category_id' => $category->id,
                    'sku' => $p['sku'], // ✅ required (NOT NULL)
                    'name' => $p['name'],
                    'slug' => Str::slug($p['name']),
                    'description' => $p['description'],
                    'price' => $p['price'],
                    'image_url' => $p['image_url'],
                    'stock' => $p['stock'],
                    'is_active' => true,
                ]
            );
        }
    }
}
